// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHckyjmim81x-eY_16wmFnWq1hKtsYM64',
    appId: '1:26633974206:web:bbe49081388f68239989ef',
    messagingSenderId: '26633974206',
    projectId: 'pet-shop-896de',
    authDomain: 'pet-shop-896de.firebaseapp.com',
    storageBucket: 'pet-shop-896de.appspot.com',
    measurementId: 'G-7P737KXB2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbqluaQTfj9yPC9kA1xDaA0tWBF3KJ-GE',
    appId: '1:26633974206:android:fa6d55d03abfc1739989ef',
    messagingSenderId: '26633974206',
    projectId: 'pet-shop-896de',
    storageBucket: 'pet-shop-896de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC087qV4JsKKNmlsZWUFT3ZHwksdJkPaUQ',
    appId: '1:26633974206:ios:acb093555089f5319989ef',
    messagingSenderId: '26633974206',
    projectId: 'pet-shop-896de',
    storageBucket: 'pet-shop-896de.appspot.com',
    iosBundleId: 'com.example.pets1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC087qV4JsKKNmlsZWUFT3ZHwksdJkPaUQ',
    appId: '1:26633974206:ios:1ae79a2e6ee9b3c49989ef',
    messagingSenderId: '26633974206',
    projectId: 'pet-shop-896de',
    storageBucket: 'pet-shop-896de.appspot.com',
    iosBundleId: 'com.example.pets1.RunnerTests',
  );
}
